
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.bpm-master.url}
          username: ${datasource.bpm-master.username}
          password: ${datasource.bpm-master.password}



# xxl-job 执行器配置
xxl:
  job:
    admin:
      # 调度中心
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://127.0.0.1:9091/xxl-job-admin}
      # 调度中心和执行器之间的通信密码（自己生成，如：openssl rand -hex 32）
      access-token: ${XXL_JOB_ACCESS_TOKEN:}
      # HTTP 通信超时时间（秒）
      timeout: 5

    executor:
      # 为{true}时才创建执行器；如果不使用xxljob服务改成false即可；${XXL_JOB_ENABLED:false}
      enabled: false
      # 当前业务服务注册成哪个执行器组
      appname: ${spring.application.name}
      # 执行器端口：调度中心通过这个端口触发当前服务${spring.application.name}如：flycloud-system中的任务
      # 同一台服务器时不同业务服务必须使用不同执行器端口（如：flycloud-system使用9999、flycloud-mall使用10000）；不同服务器时可使用同一个执行器端口
      port: 10001
      # 业务服务xxl-job的日志，比如：XxlJobHelper.log("xxx")
      log-path: ./logs/xxl-job/${spring.application.name}
      # 日志最多存活天数
      log-retention-days: 30