
# 平台服务
server:
  port: 8085

spring:

  application:
    name: "@artifactId@"
  profiles:
    active: @profiles.active@

  main:
    allow-circular-references: true # 允许循环依赖 (多层架构下无法避免这个情况)
    allow-bean-definition-overriding: true # 允许 Bean 覆盖 (如 Feign 等会存在重复定义的服务)

  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@

      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        username: @nacos.username@
        password: @nacos.password@
        namespace: "@nacos.namespace@"
        group: @nacos.discovery.group@

      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        username: @nacos.username@
        password: @nacos.password@
        namespace: "@nacos.namespace@"
        group: @nacos.config.group@
        file-extension: yaml

  config:
    import:
      - optional:nacos:application-common.yaml?group=@nacos.config.group@&refreshEnabled=true
      - optional:nacos:application-datasource.yaml?group=@nacos.config.group@&refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?group=@nacos.config.group@&refreshEnabled=true


client:
  oauth2:
    client:
      client-id: appId # 客户端标识 ID
      secret: 123456 # 客户端安全码
      scope: server
      #默认放行、服务间调用需要放行
      ignore-urls:
        # - /actuator/**
        - /v2/api-docs-ext
        - /cas/sso/**
        - /sso/**
        - /im/ws/**

  elasticsearch:
    rest:
      uris: http://101.34.33.33:9200
