
# note 开发环境配置示例，拷贝和改成nacos-dev.properties放到config/nacos下，不要提交该文件 -> .gitignore 加：/config/nacos/nacos-dev.properties

nacos.server=127.0.0.1:8848
nacos.username=nacos
nacos.password=nacos
nacos.namespace=
nacos.discovery.group=DEFAULT_GROUP
nacos.config.group=DEFAULT_GROUP
