
# 授权服务
server:
  port: 8088

spring:

  application:
    name: "@artifactId@"
  profiles:
    active: @profiles.active@

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  cloud:
    nacos:
      server-addr: ${nacos.server:127.0.0.1:8848}
      username: ${nacos.username:nacos}
      password: ${nacos.password:nacos}

      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${nacos.namespace:}
        group: ${nacos.discovery.group:DEFAULT_GROUP}

      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${nacos.namespace:}
        group: ${nacos.config.group:DEFAULT_GROUP}
        file-extension: yaml

  config:
    import:
      - optional:nacos:application-common.yaml?group=${nacos.config.group:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:application-datasource.yaml?group=${nacos.config.group:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?group=${nacos.config.group:DEFAULT_GROUP}&refreshEnabled=true

