
# 出现错误时, 直接抛出异常
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

# getErrorPath()@deprecated since 2.3.0 in favor of setting the property `server.error.path`
server:
  error:
    path: /error