
# spring 配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 5000MB

  # bean重名覆盖
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  #jackson配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 格式化输出
      INDENT_OUTPUT: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  cloud:
  # sentinel 配置
  # sentinel:
  #   # sentinel 开关
  #   enabled: true
  #   # 取消控制台懒加载
  #   eager: true
  #   transport:
  #     # dashboard控制台服务名 用于服务发现
  #     # 如无此配置将默认使用下方 dashboard 配置直接注册
  #     server-name: ruoyi-sentinel-dashboard
  #     # 客户端指定注册的ip 用于多网卡ip不稳点使用
  #     # client-ip:
  #     # 控制台地址 从1.3.0开始使用 server-name 注册
  #     # dashboard: localhost:8718

  # redis 通用配置 子服务可以自行配置进行覆盖
  data:
    redis:
      # 111.228.51.252  39.98.125.88  laixueshi.cn  除了项目在服务器上域名可以代替ip；本地运行不行，但可以在host新增域名映射ip可实现
      host: 39.98.125.88
      port: 6379
      # 密码(如没有密码请注释掉password字段)
      password:
      database: 0
      timeout: 5s
      connect-timeout: 5s
      ssl:
        enabled: false
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 3s
        shutdown-timeout: 100ms


# redisson 配置
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${spring.application.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50


# security授权公共配置
security:
  auth:
    token:
      # 登录态有效期，单位秒，默认2小时；接口请求认证成功后会滑动续期
      login-timeout-seconds: 7200
      # refresh token 有效期，默认30天，单位秒
      refresh-token-timeout-seconds: 2592000

    # 白名单 (授权、swagger、监控中心等url)
    ignore-urls:
      - /oauth/**
      - /auth/**
      - /feign/**
      - /gen/**
      - /app/**
      - /static/**
      - /actuator/**
      - /webjars/**
      - /druid/**
      - /assets/**
      - /v2/api-docs/**
      - /v3/api-docs/**
      - /swagger/api-docs
      - /swagger-ui.html
      - /swagger-resources/**
      - /doc.html

    # 是否启用网关验证（是：接口都拦截验证；否：全部接口在网关服务都为白名单）
    gateway-enable: true


# 上传配置
upload:
  config:

    # 使用的服务器类型 (1:本地服务, 2:ftp服务器, 3:sftp服务器, 4:阿里云oss对象存储, 5:华为云obs对象存储, 9:smb共享文件夹)
    use-server-type: 3

    # sftp服务器配置
    local-server-config:
      # 文件上传和读取的前缀真实路径
      base-path: /Users/lxs/applicationFile/file/person/flycloud-server/
      # 拼给前端或客户端展示的前缀url路径
      base-url: http://localhost:8080/static/

    # sftp服务器配置
    sftp-server-config:
      ip:
      user: root
      password:
      port: 22
      base-path: /project/upload-file/
      # base-url: http://111.228.51.252:8080/static/
      base-url: http://111.228.51.252:8888/static/



# springdoc 配置
springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据
    persistAuthorization: true


# swagger 配置
swagger:
  enabled: true
  title: Fly Swagger API
  gateway: http://localhost:8080
  token-url: ${swagger.gateway}/auth/oauth/token
  scope: server
  services:
    flycloud-gateway: flycloud-gateway
    flycloud-system: flycloud-system
    flycloud-mall: flycloud-mall
    flycloud-music: flycloud-music
    flycloud-generator: flycloud-generator
    flycloud-job: flycloud-job
    flycloud-test: flycloud-test
