
# spring 配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 5000MB

  # bean重名覆盖
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  #jackson配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 格式化输出
      INDENT_OUTPUT: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  cloud:
  # sentinel 配置
  # sentinel:
  #   # sentinel 开关
  #   enabled: true
  #   # 取消控制台懒加载
  #   eager: true
  #   transport:
  #     # dashboard控制台服务名 用于服务发现
  #     # 如无此配置将默认使用下方 dashboard 配置直接注册
  #     server-name: ruoyi-sentinel-dashboard
  #     # 客户端指定注册的ip 用于多网卡ip不稳点使用
  #     # client-ip:
  #     # 控制台地址 从1.3.0开始使用 server-name 注册
  #     # dashboard: localhost:8718

  # redis 通用配置 子服务可以自行配置进行覆盖
  data:
    redis:
      # 111.228.51.252  39.98.125.88  laixueshi.cn  除了项目在服务器上域名可以代替ip；本地运行不行，但可以在host新增域名映射ip可实现
      host: 39.98.125.88
      port: 6379
      # 密码(如没有密码请注释掉password字段)
      password:
      database: 0
      timeout: 5s
      connect-timeout: 5s
      ssl:
        enabled: false
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 3s
        shutdown-timeout: 100ms


# redisson 配置
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${spring.application.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50


# websocket公共配置；此处path: /ws目前由flycloud-system统一引入websocket模块实现，其他服务调用api接口WebSocketSenderApi即可
websocket:
  enabled: true
  path: /ws
  # local、redis；local：单机部署，如flycloud-system 只有一个实例
  sender-type: local


# security授权公共配置
security:
  auth:

    # token配置
    token:
      # 登录态有效期，单位秒，默认2小时；接口请求认证成功后会滑动续期
      login-timeout-seconds: 7200
      # refresh token 有效期，默认30天，单位秒
      refresh-token-timeout-seconds: 2592000

    # feign配置
    feign:
      # 是否启用服务间Feign内部接口签名验证
      enabled: true
      # Feign内部接口签名密钥，各个服务必须保持一致
      secret: flycloud-feign-secret
      # Feign签名时间戳有效期，单位秒
      expire-seconds: 300

    # 白名单配置 (授权、swagger、监控中心等url)
    ignore-urls:
      - /admin/auth/**
      - /app/auth/**
      - /captcha/**
      - /app/**
      - /gen/**
      - /static/**
      - /actuator/**
      - /webjars/**
      - /druid/**
      - /assets/**
      - /css/**
      - /swagger-ui/index.html
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger/api-docs
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs/**
      - /v3/api-docs
      - /v3/api-docs/**

    # 是否启用网关验证（是：接口都拦截验证；否：全部接口在网关服务都为白名单）
    gateway-enable: true

  # ras密钥对配置
  rsa:
    keys:
      # 登录密码
      fly_cloud_login_password:
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqG/pmVfnO8KrCL1zHzsnx2hlwmbvFqSGna89QU9a5q0JO+pdeppBhHbHI8Lao/Hsk4jSQbA1C+vSKi018A6a4WILlbRMYZaStouc2abYCZsejL/SMccsCFz+c06WPzFJ5VkxAoTTmVJ0pCViVJEZdQuXMc7GtQRP7VME+DhrVDThII6s/2oxJLNhPxCejGZz84jhekHIedF38/SRz2gj5QQH3v+zYC2SWjH+WAoyLckFQ7A3FBYt9qaFTLA1ObpSmKEeZZvxWadovMW2gw6tQPWbzxalY00Dhei7hGi8yU29bhF032SQaMIgyuIiYW4wLdk2wdjOY1JtJDGgjhmjXwIDAQAB
        private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCob+mZV+c7wqsIvXMfOyfHaGXCZu8WpIadrz1BT1rmrQk76l16mkGEdscjwtqj8eyTiNJBsDUL69IqLTXwDprhYguVtExhlpK2i5zZptgJmx6Mv9IxxywIXP5zTpY/MUnlWTEChNOZUnSkJWJUkRl1C5cxzsa1BE/tUwT4OGtUNOEgjqz/ajEks2E/EJ6MZnPziOF6Qch50Xfz9JHPaCPlBAfe/7NgLZJaMf5YCjItyQVDsDcUFi32poVMsDU5ulKYoR5lm/FZp2i8xbaDDq1A9ZvPFqVjTQOF6LuEaLzJTb1uEXTfZJBowiDK4iJhbjAt2TbB2M5jUm0kMaCOGaNfAgMBAAECggEAAjZzMgp7CVv2CDs1ajBVYfzRYveAYG3LAZ6jhN0kVeMK3TUiHu83cOclxIVjq20HlZrAdsgOZR+WZ77e3UjHqKb2W/RAohkJZGgfEiyi/cXV4Dr9Tb9y67MH/4/TW8NKR2A4usCAmXVPNjgIdhxq0ZvqkOyzDmJGAm+0kIHyRntZRO5bkAWEv/NW+hMhb2TkybORq6XVH76ugeniUgL2DiAv2um6uOc1fgXYJL4axA0HdK67K8XGjRmgdzRgZmFxeg2AfnNhbMfvKxAR+p0imnzpgLIBlckR7ZPiyqhT06GgCsfU4Aj/j302fX44vLhBkmfAiqTOw7uomLnTjlpd+QKBgQDh1mrknQpDjpD4tHUabERcffiNp/o6oks4olq7DWgMsem2c8qN2nHB43bD9vgXmHMqCcvl36BSC+SfOS+JS7a/HRCktoxxktDz6HWUsvjy1L6G5FITqW2rMmCnmXUZuEhu0eiQGBlAjDYxGyFO6PMwu0A0CCF9f1j0oB2OCmRFJwKBgQC+7uzTjSz2J3lGoUpjVPu5diSRuOtzE6Czgm5czcJMnpMybqWy83hhBh9kdFMkyGYHFk8sqxzpt1cd/vsIady0S8Fc384msqWTmyg6t1n1GZyNZyENddRw78lpPqIzI5FaaMS7AgoPZ5mP+aWLIn8JBlfUNugvt6CbYRDJ6fZDCQKBgAP6BJPV+BJMdl0KwG0grut6BGBqLsvNg8mRgkt85vIiR91AmLZ6vDoPyU2WEbRIqO56ka6Qi4AmWXY8SYv/W05uMpbT6BEv5qIE290scZnFCT3S02cpOpcjIfSRjTBQwGXDKHcxFXC/h0zCD4oWLAIVqgHAiuZs0aItF5gisrVNAoGAayLaFOL0xbLkpDNA8HfxP+IBJxuiUlJDLDcWAlEao6+fXP8lT0K624Z5+v4i4VLpnTRxfNkPQj20ToqTBeeRBkIz4A9dN+2qZyb67eeQPK4AYH/r1ge2CyEh3UJd9WAR4a9EJMNCLd6uFlG5CFd0/PVoNxYQNyZMoqNWrlXv7zECgYAPYlBo3g674eI3Qb0CGpb5o0zLzV5jR+6ubJ1nkwr9X9YJOAJ/8QtbrRfE1DCjQ/p5p/rdl4YKEeZWidZcrIJCdKjCPj1sN91vVVWUmGs8J35lcABC70zgO43jxlHNpel/rpuztrVqZBBGez/7TPfYthzdgh8cD5SkweUVaQQ0Cw==

      # 支付密码
      fly_cloud_pay_password:
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAolvhZzAaDugJQ/kADME7zxv2EbQR4377PWliPTbk8cZh+PoSi6EviwN1syWMLJGs8RwuaGFcUQwvXvrTCo/E2nrg1c7odOYTHnEi172Wu9mVUUGoxZ6vNCTXnwyK34u+136IcTunepP/LC+RxSzB/Qk81PJX+Fx3ffXoAclcQWvI2ssTabVYyf8zKnEF5F151qp0PuYYDGNOrYXbbblUjg0BbhVVPINUz7lhMENqPFwz2lAk6GCLlYMvkbIhN9mjcDMCQu3uPTtjadpMaypBniwVuXfqTGMvQ5LxWfHzMutiKNjTU3F4qsTbXslPLMlclIDRCu648Bkj7tB+19tQuQIDAQAB
        private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiW+FnMBoO6AlD+QAMwTvPG/YRtBHjfvs9aWI9NuTxxmH4+hKLoS+LA3WzJYwskazxHC5oYVxRDC9e+tMKj8TaeuDVzuh05hMecSLXvZa72ZVRQajFnq80JNefDIrfi77XfohxO6d6k/8sL5HFLMH9CTzU8lf4XHd99egByVxBa8jayxNptVjJ/zMqcQXkXXnWqnQ+5hgMY06thdttuVSODQFuFVU8g1TPuWEwQ2o8XDPaUCToYIuVgy+RsiE32aNwMwJC7e49O2Np2kxrKkGeLBW5d+pMYy9DkvFZ8fMy62Io2NNTcXiqxNteyU8syVyUgNEK7rjwGSPu0H7X21C5AgMBAAECggEAScNyud3pyOH067PiKOlV0ffDKTHlerVDUhhh8KvTAmF+O47qBBQcNI1C2Txy3gDlULnb/8JUHeJqVz2fykmdRyHSqnERvaKWBxuhl+Dj7b6iD0PEeNxqf0dJy1H4ei3Ua7VqKf/PTGqW4S1PjgSSsfKTd7AO9aCVDV4+pSklx/aF+2l4Gq/HsjBCu5GcbCdEK6s1Bbi+yk6kO6WK1noB/14owQxI38mfR/IX5eUO3nMx9wsh8LjMpuZzhi9FQmIrWUXjhG5zjCy/wnE5X2IWVUKfiXwDtxYzMtFQTb8X8Nw7sub1AaApceedgFNrWzYHy+ks/5MtZGiIlZsav5WPXQKBgQDR4XS9iwK4WPhMGOoAfOCYPfi3tm/GofuhxWgIKdQu/K4HXhUBhLGpva/5ZPfURCklpGlCpxofKM4e1QUBPk8SVB7Gs6iwnFnwQRMtWwuY92pQFc2mhzfstHg0taREoHEK7EYXaskCekng29Qv/Cv4+agkufeOE1oJeCprjh+LCwKBgQDGCSdCCI2MtbTqHRJDSOZDC3AADWUgaFrgkYnV4PhOpR5sYJaZr7uY2MfZMw3Y0C0RX1wW4isUSn7lPmkWKLa8co3II8oYKZDy9KHXwYyIYXwUcivbn7wdEoa5c5W1Yc3dHuNL3ZvA5S4gtlAdggYyR5pA9R0O7EZY20wl0amNywKBgQDP9zIBGvxwBKDMbqd4IkU+NbH9AAZT8W/whTYnWKNKh9A9tqjj30NYKYB0g+raZ0vKY9Z1WDUXCQztGjEiYUZip/3y8FTH47VuzlydRakBQrASePhU+Ymdv9mYiSAjbEN3ClYNoB9bmCcaa1kezyYXR/Knqao2GtDNr0eBWcvBrwKBgB7y20HEmGp/EzDrLil5wRKFPRGlBkLUTC+ATywvpl6UC3cgeSi3f/fZGRJmmiliD0kBwCCLY/Qd2Er3P/EIl9ZHiMTYYwL3rAFsHcbcJpxBr+R6G0SNaBabCJb+60yXZlbCNv9qOKciqdzO4SJbaaB99Ctmow3r+up0Cyh15auVAoGBAKHy4T304eNlo35KvI4MTY2FiXIXvuYc7HaXA9jyeqNdk3uhluT/6M9VWPFk+UzX07mQPtxP2qV8ADWuzon46ZeNXmzXXlMN6vQPJDBX8vfwEhAWv0GUc1rkxmjkQbOeDUx/mYDSDJUtO4kTN2DqMrm93XNqvezavznr02/hJZl8

      # 开放接口
      fly_cloud_open_api:
        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs7IakV0YmQLRbqT2Vlv2s4ODvb7d7PMeaDyz7g5jvKbuIkxdUU7KRHl+PXXdzH4MiBpl3sq8+oAYfZqwq8+wYkdgZhuAqjIoW6DHoQZXRXF1SrQ6kF4j5PuangfAfh1xp5MkHkc2Xy3qvshplh5eE7odhO3mYhnM9GpRB4w8uJItEX9K0X0XuVhX7t+P9nwBkCm13JBS1WdTxPF9rom+SPxisgsEqhEks9uPyW9ioTL4zsLsHskgy3XsTARla9uI3ggUVLD0Y/yqII5sZ97hUc0GvzoDHysnQmB7jp1MTjspojD+zXmB+aT/NvDi++iN2x9UXbhY/YAcDCexORVEDwIDAQAB
        private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzshqRXRiZAtFupPZWW/azg4O9vt3s8x5oPLPuDmO8pu4iTF1RTspEeX49dd3MfgyIGmXeyrz6gBh9mrCrz7BiR2BmG4CqMihboMehBldFcXVKtDqQXiPk+5qeB8B+HXGnkyQeRzZfLeq+yGmWHl4Tuh2E7eZiGcz0alEHjDy4ki0Rf0rRfRe5WFfu34/2fAGQKbXckFLVZ1PE8X2uib5I/GKyCwSqESSz24/Jb2KhMvjOwuweySDLdexMBGVr24jeCBRUsPRj/Kogjmxn3uFRzQa/OgMfKydCYHuOnUxOOymiMP7NeYH5pP828OL76I3bH1RduFj9gBwMJ7E5FUQPAgMBAAECggEAB6cxC3owDIA6uYrMClnd/r+TUkxOjli9CvUe4qd5PEp4ajyKCDxMpVrunfZ8TPPHW9qSoR5NqyDef3xMREeoUZ827f0DifwbN5Ui5hWWN5kWmj5lH3Xq8xsmIXnfYF+np1qUbLeytfNc2TrsMvO1z62bCT4f6ZNYunDMD6q7gU7MmJdsEvh7CgWhlH59Lax72SlvbqcwCq9sB06kWxKLBN6ztB+pi/j5n/lh59Zq8m06jIsakyF5BItqchyBj3p5/IDshymblIme9VJq3U0n7bsIPFmItBzL2j/6Gek+gH2zxyP2/lyeTVqT4ASC0pFy6T3aRoLPKqolq75IU3dqrQKBgQD9BodKx2rvHbMMSHUzlQ1GrwqBlZyqjszzLkC8edS5IVVzpFJeg7hv2XioUn0B8uz7JCKuhO+JE+e5HvF+Oky2BQ4C5Y27SllCFN7L2BIqD92XapXF8dEdACjeD2k1/uqc2X5RvzQuih85NWRMLanqaM7ZTe8WXlOpwwH2AwDK+wKBgQC1zuRPvJwxdWI5nbIpAO4vcIMbYgc0uQ4XJb1OHF2DSlEEl70NFz3a0Ev0g6aP3l0DqhOv94z+m46ZJgvqshEND0g1eKnvNUHtCrgYELzna3yy6DDiLfaTQBurkhDQddkX35MY8nw8EL48RH+YV6DmnMlBoNCkfLhU0uGjwSXe/QKBgQCzgw45X4HeY5PEAyQjlHv2yfkKNrsPxoBhh08maMkjDyMxCEPoCkuwDvorcVp/J3o6M0jnyCipeBXOoMV0aKhD+xIVvAbx+a2Z1HS86m74qIjuBBB+fzF9Ab/8y7I5PMH2xdd45859tkCwtdCSu1Lxm6olQcV+eS2iI1gg0cCeQQKBgQCmPKqeDgNzZbWOoRaKT4N6dRIsM5ILLzonCCb0CROoPIef/26pTZsNPHB2/vmJivTZqOWffGa7V1knx5YV3wOgQVzxJ4eaZcQGDksOFh/kKnA21f/8j7JqKbAjTMd7FIaQQamqoe3eriCD0s4oadeBhdKv429jN3cEeF5A8RbDsQKBgQCPqT+L2LuvaonAixmXe+OWsS4xvqt4OjpqSV5WenBcC5AjGpMtpOKpeToTif7wK5XNgRulArg+zogFxRHMT4b+V3u6GrXLpLUbKGC/JkEG5rO9YtGLFcyHsC9J8Tsw9j2f9VZvzelVMT4fRhXp4cW6U1FM/3kP9otOjvEmjiLBbA==


# 上传配置
upload:
  config:

    # 使用的服务器类型 (1:本地服务, 2:ftp服务器, 3:sftp服务器, 4:阿里云oss对象存储, 5:华为云obs对象存储, 9:smb共享文件夹)
    use-server-type: 3

    # 本地服务器配置
    local-server-config:
      # 文件上传和读取的前缀真实路径
      base-path: /Users/lxs/applicationFile/file/person/flycloud-server/
      # 拼给前端或客户端展示的前缀url路径
      base-url: http://localhost:8080/static/

    # sftp服务器配置
    sftp-server-config:
      ip:
      user: root
      password:
      port: 22
      base-path: /project/upload-file/
      # base-url: http://111.228.51.252:8080/static/
      base-url: http://111.228.51.252:8888/static/



# springdoc 配置
springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据
    persistAuthorization: true


# swagger 配置
swagger:
  enabled: true
  title: Fly Swagger API
  gateway: http://localhost:8080
  token-url: ${swagger.gateway}/auth/oauth/token
  scope: server
  services:
    flycloud-gateway: flycloud-gateway
    flycloud-system: flycloud-system
    flycloud-mall: flycloud-mall
    flycloud-music: flycloud-music
    flycloud-generator: flycloud-generator
    flycloud-job: flycloud-job
    flycloud-test: flycloud-test
