
spring:
  cloud:
    # 网关配置
    gateway:
      metrics:
        enabled: true
      # 打印请求日志(自定义)
      requestLog: true
      discovery:
        locator:
          # 开启服务注册和发现
          enabled: true
          # 自动配置路由 (手动写路由的话, swagger整合不了)
      routes:

        # swagger接口地址重写 (只改变转发路由,无其他修改), 如将 https://localhost:8080/v3/api-docs/flycloud-system 这个路径重写为 https://localhost:8080/flycloud-system/v3/api-docs
        - id: openapi
          uri: lb://flycloud-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: flycloud-system              # 路由id，没有固定规则但要求唯一, 建议配合服务名
          # uri: http://localhost:8001     # 目标地址, 即断言匹配后跳转的路由地址 (即类似nginx的代理地址)
          uri: lb://flycloud-system
          order: 1
          predicates:                      # 断言（判断条件）
            - Path=/flycloud-system/**     # 断言, 路径相匹配的进行路由; 服务一般不用设置servlet-context-path,因为直接让客户端请求带上此断言服务名字即可 (即类似nginx的断言)
          # filters:
            # - StripPrefix=1              # 去除第一个路径 (http://localhost:8080/aaa/order/orderInfo -> http://localhost:8080/order/orderInfo)
            # - PrefixPath=/order          # 请求路径添加前缀 (http://localhost:8080/order/orderInfo -> http://localhost:8080/aaa/order/orderInfo)

            # - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            # 路由重写 (断言之前执行), 如将 https://localhost:8080/v3/api-docs/flycloud-system 这个路径重写为 https://localhost:8080/flycloud-system/v3/api-docs

        - id: flycloud-mall
          uri: lb://flycloud-mall
          predicates:
            - Path=/flycloud-mall/**

        - id: flycloud-generator
          uri: lb://flycloud-generator
          predicates:
            - Path=/flycloud-generator/**
            -
        - id: flycloud-test
          uri: lb://flycloud-test
          predicates:
            - Path=/flycloud-test/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE