
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.mall-master.url}
          username: ${datasource.mall-master.username}
          password: ${datasource.mall-master.password}


#       其他数据库系统-参数说明:          
#        oracle:
#          type: ${spring.datasource.type}
#          driverClassName: oracle.jdbc.OracleDriver
#          url: ${datasource.mall-oracle.url}
#          username: ${datasource.mall-oracle.username}
#          password: ${datasource.mall-oracle.password}
#          hikari:
#            connectionTestQuery: SELECT 1 FROM DUAL

#        postgres:
#          type: ${spring.datasource.type}
#          driverClassName: org.postgresql.Driver
#          url: ${datasource.mall-postgres.url}
#          username: ${datasource.mall-postgres.username}
#          password: ${datasource.mall-postgres.password}
