
spring:
  cloud:
    # 网关配置
    gateway:
      metrics:
        enabled: true
      # 打印请求日志(自定义)
      requestLog: true
      discovery:
        locator:
          # 开启服务注册和发现
          enabled: true
          # 自动配置路由 (手动写路由的话, swagger整合不了)
      routes:

        # 固定路由转发配置 无修改
        - id: openapi
          uri: lb://flycloud-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: flycloud-system     # 路由id，没有固定规则但要求唯一, 建议配合服务名
          # uri: http://localhost:8001     # 匹配后提供服务的路由地址 (即类似nginx的代理地址)
          uri: lb://flycloud-system
          order: 1
          predicates:
            - Path=/flycloud-system/**      # 断言, 路径相匹配的进行路由; 服务一般不用设置servlet-context-path,因为直接让客户端请求带上此断言服务名字即可 (即类似nginx的断言)
          # filters:
            # - StripPrefix=1     # 去除第一个路径 (http://localhost:8001/aaa/order/orderInfo -> http://localhost:8001/order/orderInfo)
            # - PrefixPath=/order     # 请求路径添加前缀 (http://localhost:8001/order/orderInfo -> http://localhost:8001/aaa/order/orderInfo)

        - id: flycloud-mall
          uri: lb://flycloud-mall
          predicates:
            - Path=/flycloud-mall/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE