
# application-dev.example.yml
# note 开发环境配置示例，拷贝和改成application-dev.yml放到resources下，不要提交该文件 -> .gitignore 加：**/src/main/resources/application-dev.yml

xxl:
  job:
    datasource:
      url: "jdbc:mysql://127.0.0.1:3306/fly_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai"
      username: "root"
      password: "root"
    mail:
      host: "smtp.qq.com"
      port: 25
      username: ""
      from: ""
      password: ""
    access-token: ""
