
# application-local.yml

xxl:
  job:
    datasource:
      url: "jdbc:mysql://127.0.0.1:3306/fly_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai"
      username: "root"
      password: ""
    mail:
      host: "smtp.qq.com"
      port: 25
      username: ""
      from: ""
      password: ""
    access-token: ""
