# Actuator 配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

spring:
  jackson:
    time-zone: GMT+8

maku:
  xss:
    enabled: true

#easy trans 数据翻译组件
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true    